# (ES) - Nota: dependiendo de tu hardware la base datos podría tardar más o menos en estar disponible.
# (EN) - Note: Depending on your hardware, the database may take more or less time to become available.

services:
  wordpress:
    image: wordpress-chmodmasx:6.7.2-php8.4
    container_name: wordpress
    depends_on:
      - mysql
      - redis
    ports:
      - 8099:80  
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WP_MEMORY_LIMIT: 512M
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_MAX_FILESIZE: 1024M
      PHP_POST_MAX_SIZE: 1024M
      PHP_MAX_EXECUTION_TIME: 600
      PHP_MAX_INPUT_VARS: 4000
    volumes:
      - your_path/wordpress_data:/var/www/html
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_wp
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - your_path/mysql_data:/var/lib/mysql
    restart: always

  memcached:
    image: memcached:alpine
    container_name: memcached_wp
    command: memcached -m 64
    network_mode: "service:wordpress"
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_wp
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma_wp
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql
    restart: always
